POST http://localhost:5001/api/v1/appointment HTTP/1.1
content-type: application/json

{
    "appointmentDate": "2022/08/18",
    "weight": 5.78,
    "size": 78,
    "age": "2 años",
    "brainPerimeter": 15,
    "bodyMassIndex": 5,
    "prolongedDiagnosis":[
        {
            "diagnosis":"Diabetes",
            "age": "3 meses"
        },
        {
            "diagnosis":"No se",
            "age": "2 meses"
        }
    ],
    "characteristicsAttention":{
        "sickTime":"3 dias",
        "Relato": "Se encontraba con malestar general",
        "Reevaluacion": "Se reevaluara en 3 dias"
    },
    "vitalFunctions": {
        "fr":37,
        "fc":15,
        "t": 36,
        "saturacion": 95
    },
    "diagnosis":[
        {"diagnosticName":"Gripe"},
        {"diagnosticName":"Infeccion estomacal"}
    ],
    "longTreatment":[
        {
            "longTreatmentName":"Eutirox",
            "status": 1,
            "suspensionDate":null
        },
        {
            "longTreatmentName":"Ranttt",
            "status": 1,
            "suspensionDate":null
        }
    ],
    "treatment":[
        {"nameTreatment":"Ibuprofeno"},
        {"nameTreatment":"Paracetamol"}
    ],
    "auxiliaryExams":[
        {"exams":"Orina"},
        {"exams":"Sangre"}
    ],
    "percentiles": {
        "percentileWeight":37,
        "heightPercentile":15,
        "percentilMC": 36
    },
    "status": 1
}
