POST http://localhost:5000/api/v1/patient HTTP/1.1
content-type: application/json

{
    "NumberHC": "00001",
    "DNI": "75687381",
    "Name ":   "Lisbeth",
    "LastName": "Ortogorin Condori",
    "DateBirth":  "1996/02/08",
    "Gender":  "F",
    "BirthWeight":  "3.78",
    "Childbirth":   "Natural",
    "Apgar":    3,
    "SupplementaryFeeding":   "NO",
    "Lactation":  "12 meses",
    "Gestation":    "9 meses",
     "Vaccines": [{
        "Name":"HCD" ,
        "Eigth": "3 meses"
    },
    {
        "Name":"HB" ,
        "Eigth": "2 meses"
    }],
    "Estate": 1
}

