// /api/v1/patient/:IdUser
POST http://localhost:5001/api/v1/patient/634df7a6128e2ed1e2143f05 HTTP/1.1
content-type: application/json

{
  "numberHC":"HC-0001",
  "dni":"75687383",
  "name":"Lisbeth",
  "lastname":"Ortogorin Condori",
  "birthDate":"1996/02/08",
  "gender": "F",
  "birthWeight":3.78,
  "childBirth":"Natural",
  "apgar":"3",
  "supplementaryFeeding":1,
  "lactation": "12 meses",
  "gestation": "9 meses",
  "vaccines": [{
    "name": "HCD"
  },
  {
    "name": "HB"
  }],
  "state": 1
}
