POST http://localhost:5000/api/v1/patient/createPatientToUserHandler/630ba9e3660e3b400e4d3531 HTTP/1.1
content-type: application/json

{
    "NumberHC": 35,
    "DNI": "75687383",
    "Name": "Lisbeth",
    "LastName": "Ortogorin Condori",
    "DateBirth":  "1996/02/08",
    "Gender":  "F",
    "BirthWeight":  3.78,
    "Childbirth":   "Natural",
    "Apgar":    "3",
    "SupplementaryFeeding":   1,
    "Lactation": "12 meses",
    "Gestation": "9 meses",
    "Vaccines": [{
        "Name":"HCD" ,
        "age": "3 meses"
    },
    {
        "Name":"HB" ,
        "age": "2 meses"
    }],
    "Estate": 1
}
