POST http://localhost:5001/api/v1/user HTTP/1.1
content-type: application/json

{
"name":"test12",
"surname":"surname test",
"email":"test80@gmail.com",
"dni":"123456778",
"phone":"1234566",
"level":"admin"
}
