PUT http://localhost:5001/api/v1/user/63227f558df0fd44529b0fe5 HTTP/1.1
content-type: application/json

{
"name":"test17",
"surname":"surname test",
"email":"test17@gmail.com",
"dni":"123456778",
"phone":"1234566",
"level":"admin"
}
